sudo: required
services:
  - docker
before_install:
  - docker build -t mohamedthowbick/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true mohamedthowbick/react-test npm run test
after_success:
  - docker build -t mohamedthowbick/multi-client ./client
  - docker build -t mohamedthowbick/multi-nginx ./nginx
  - docker build -t mohamedthowbick/multi-server ./server
  - docker build -t mohamedthowbick/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them into docker hub
  - docker push mohamedthowbick/multi-client
  - docker push mohamedthowbick/multi-nginx
  - docker push mohamedthowbick/multi-server
  - docker push mohamedthowbick/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-629830000026"
  # elasticbeanstalk-ap-southeast-1-629830000026
  # http://dockerreact-env.eba-2b8wgitw.ap-southeast-1.elasticbeanstalk.com/
  bucket_path: "docker-multi"
   on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY